cliente/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
	url(r'^new', views.ClienteInsert.as_view(),
		name= "cliente_insert"),
	url(r'^list$', views.ClienteList.as_view(),
		name='cliente_list'),
    url(r'^cliente/update(?P<pk>[0-9]+)/$', views.ClienteUpdate.as_view(),
        name='cliente_update'),
    url(r'^cliente/detail(?P<pk>[0-9]+)/$', views.clienteDetail,
        name='cliente_detalle'),
	# url(r'^cliente/delete(?P<pk>[0-9]+)/$', views.ClienteDelete.as_view(),
	#  	name="cliente_delete"),
	# url(r'^(?P<pk>[0-9]+)/$', views.cliente_detail,
	# 	name="cliente_detail"),
]

plataforma/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import (
handler400, handler403, handler404, handler500
)
# from usuario import views as usuario_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('usuario.urls', namespace='usuario')),
    url(r'^producto/', include('producto.urls', namespace='producto')),
    #url(r'^', include('proveedor.urls', namespace='proveedor')),
    #url(r'^', include('inventario.urls', namespace='inventario')),
    url(r'^cliente/', include('cliente.urls', namespace = 'cliente')),
    url(r'^', include('factura.urls', namespace = 'factura')),
]+	static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

cliente/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

class Cliente(models.Model):
    TIPO_CUENTA = (
		('corriente', 'Corriente'),
		('ahorros', 'Ahorros'),
		('recaudo','Recaudo'),
		)
    dni = models.CharField(max_length=15,
        unique=True, verbose_name= 'Número de Identificación')
    nombreEmpresa = models.CharField(max_length=45, null=True, blank=True,
        verbose_name= 'Nombre empresa')
    nombreRepresentante = models.CharField(max_length=45,
        verbose_name= 'Nombre representante')
    apellidoRepresentante = models.CharField(max_length=45,
        verbose_name = 'Apellido representante')
    telefono = PhoneNumberField (default='+573041234567',
        verbose_name = 'Teléfono')
    correo = models.EmailField(max_length=100, blank=True, null=True,
        verbose_name='Correo')
    ciudad = models.CharField(max_length=25, blank=True, null=True,
        verbose_name=' Ciudad')
    direccion = models.CharField(max_length=25, blank=True, null=True,
        verbose_name='Dirección')
    banco = models.CharField(max_length=45, blank=True, null=True)
    tipoCuenta = models.CharField(choices=TIPO_CUENTA, max_length=25,
        blank=True, null=True, verbose_name='Tipo de cuenta')
    numeroCuenta = models.CharField(max_length=15, blank=True,
        null=True, verbose_name='Número de cuenta')

    def __unicode__(self):
        return self.dni

cliente/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import (
    UpdateView, CreateView, DeleteView)
from django.views.generic import ListView
from .models import Cliente
#from .forms import PerfilForm
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
#Permisos
from django.contrib.auth.mixins import (
    LoginRequiredMixin, PermissionRequiredMixin)
from django.contrib.auth.decorators import (
    login_required, permission_required)


class ClienteInsert(LoginRequiredMixin,
                    PermissionRequiredMixin, CreateView):
    permission_required = ('cliente.add_cliente')
    model = Cliente
    success_url = reverse_lazy('cliente:cliente_list')
    fields = ['dni', 'nombreEmpresa', 'nombreRepresentante',
              'apellidoRepresentante', 'telefono', 'correo',
              'ciudad', 'direccion', 'banco', 'tipoCuenta',
              'numeroCuenta', ]

class ClienteList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = ('cliente.add_cliente')
    model = Cliente
    context_object_name = 'clientes'
    # paginate_by = 5
    # def get_queryset(self, *args, **kwargs):
    #     qs = super(ClienteList, self).get_queryset(*args, **kwargs).order_by("-nombreEmpresa")
    #     return qs
    #     #funcion para paginar una lista
    # def get_context_data(self, **kwargs):
    #     context = super(ClienteList, self). get_context_data(**kwargs)
    #     context['range'] = range(context["paginator"].num_pages)
    #     return context

class ClienteUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = ('cliente.change_cliente')
    model = Cliente
    success_url = reverse_lazy('cliente:cliente_list')
    fields = ['dni', 'nombreEmpresa', 'nombreRepresentante',
              'apellidoRepresentante', 'telefono', 'correo',
              'ciudad', 'direccion', 'banco', 'tipoCuenta',
              'numeroCuenta', ]


#
# class ClienteDelete(DeleteView):
#     model = Cliente
#     success_url = reverse_lazy('cliente:cliente_listar')
#
@login_required()
@permission_required('cliente.add_cliente')
def clienteDetail(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    template = loader.get_template('cliente/cliente_detail.html')
    context = {'cliente':cliente}
    return HttpResponse(template.render(context, request))

templates/cliente/cliente_confirm_delete.html
{% extends "system_index.html" %}

{% block system_Contable %}

<a href="{%url 'cliente:cliente_list' %}"><span class="icon fa-arrow-left "></span></a>

<form method="post">
	{% csrf_token %}
    ¿Estás seguro que deseas borrar "{{ object }}"?
    <input type="submit" value="Borrar" />
</form>

{%endblock%}

templates/cliente/cliente_detail.html
{% extends "system_index.html" %}

{% block system_Contable %}

<div class="text-center">
  <h4 class="card-title">ID CLIENTE: {{cliente.dni}}</h4>
  <h4 class="card-title">EMPRESA: {{cliente.nombreEmpresa}}</h4>
</div>
<hr>

<div class="form-row">
        <div class="form-group col-md-4 ">
          Nombres: {{cliente.nombreRepresentante}} <hr>
          Apellidos:{{cliente.apellidoRepresentante}}<hr>
          Teléfono: {{cliente.telefono}}<hr>
        </div>
        <div class="form-group col-md-4 ">
          Email: {{cliente.correo}}<hr>
          Ciudad: {{cliente.ciudad}}<hr>
          Dirección: {{cliente.direccion}}<hr>
        </div>
        <div class="form-group col-md-4 ">
          Banco: {{cliente.banco}}<hr>
          Tipo de cuenta: {{cliente.tipoCuenta}}<hr>
          Numero de cuenta: {{cliente.numeroCuenta}}<hr>
        </div>
</div>
{%endblock%}

templates/cliente/cliente_form.html
{% extends "system_index.html" %}

{% block system_Contable %}
<form method="post">
	<header>
        <center><h2>Cliente </h2></center><hr>
    </header>

    {% csrf_token %}
		<div class="form-row ">
			{%for field in form %}
				<div class="form-group col-md-4 ">
					{{ field.errors }}
					{{ field.label_tag }} <br> {{ field }}
				</div>
			{% endfor %}
		</div>

    <input type="submit" value="Guardar" class="btn btn-success pull-right" />
</form>
{%endblock%}

templates/cliente/cliente_list.html
{% extends "system_index.html" %}

{% block system_Contable %}

<table class= "table table-striped table-responsive">
  <thead class="">
    <tr class="">
      <th scope="col">DNI</th>
      <th scope="col">Empresa</th>
      <th scope="col">Nombre</th>
      <th scope="col">Apellidos</th>
      <th scope="col">Teléfono</th>
      <th scope="col">Dirección</th>
    </tr>
  </thead>
  <tbody>
    {% for pr in clientes %}
    <tr>
      <td>{{pr.dni}}</td>
      <td>{{pr.nombreEmpresa}}</td>
      <td>{{pr.nombreRepresentante}}</td>
      <td>{{pr.apellidoRepresentante}}</td>
      <td>{{pr.telefono}}</td>
      <td>{{pr.direccion}}</td>
      <td class="bg-info" >
        <a href="{% url 'cliente:cliente_detalle' pr.id %}" class="fa fa-eye fa-2x"></a>
      </td>
      <td class="bg-warning" >
        <a href="{% url 'cliente:cliente_update' pr.id %}"  class="fa fa-pencil-square-o fa-2x"></a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<!--
{% if is_paginated %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link bg-success text-white" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
    </li>
    {% endif %}

    {% for i in range %}
    <li class="page-item text-success"><a class="page-link text-success" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link bg-success text-white" href="?page={{ page_obj.next_page_number }}">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}-->

{%endblock%}