cliente/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
	url(r'^new', views.ClienteInsert.as_view(),
		name= "cliente_insert"),
	url(r'^list$', views.ClienteList.as_view(),
		name='cliente_list'),
    url(r'^cliente/update(?P<pk>[0-9]+)/$', views.ClienteUpdate.as_view(),
        name='cliente_update'),
    url(r'^cliente/detail(?P<pk>[0-9]+)/$', views.clienteDetail,
        name='cliente_detalle'),
	# url(r'^cliente/delete(?P<pk>[0-9]+)/$', views.ClienteDelete.as_view(),
	#  	name="cliente_delete"),
	# url(r'^(?P<pk>[0-9]+)/$', views.cliente_detail,
	# 	name="cliente_detail"),
]

plataforma/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import (
handler400, handler403, handler404, handler500
)
# from usuario import views as usuario_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('usuario.urls', namespace='usuario')),
    url(r'^producto/', include('producto.urls', namespace='producto')),
    #url(r'^', include('proveedor.urls', namespace='proveedor')),
    #url(r'^', include('inventario.urls', namespace='inventario')),
    url(r'^cliente/', include('cliente.urls', namespace = 'cliente')),
    url(r'^', include('factura.urls', namespace = 'factura')),
]+	static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

producto/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
	url(r'^new', views.ProductoInsert.as_view(),
		name="producto_insert"),
	url(r'^list$', views.ProductoList.as_view(),
		name='producto_list'),
	url(r'^edit(?P<pk>[0-9]+)/$', views.ProductoUpdate.as_view(),
    	name='producto_edit'),
	#  url(r'^inventario/delete(?P<pk>[0-9]+)/$', views.InventarioDelete.as_view(),
	#  	name="inventario_delete"),
	url(r'^(?P<pk>[0-9]+)/$', views.producto_detail,
		name="producto_detail"),
]

producto/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db.models import signals
from django.db import models
import decimal
from django.db.models import signals

IVA = 0.19

class Producto(models.Model):
	codigo = models.CharField(max_length=25, unique=True,
		verbose_name="Código")
	producto = models.CharField(max_length=25, unique=True)
	cantidad = models.PositiveSmallIntegerField(blank=True, null=True)
	descripcion = models.CharField(max_length=45, blank=True, null=True,
		verbose_name="Descripción")
	valorCompra = models.DecimalField(max_digits=15, blank=True, null=True,
        decimal_places=2, default=0.00, verbose_name="Valor de compra")
	valorIva = models.DecimalField(max_digits=15,
		decimal_places=2, default=0.00, verbose_name="IVA")
	valorVenta = models.DecimalField(max_digits=15,
		decimal_places=2, default=0.00, verbose_name="Valor consumo paquete")
	valorDP = models.DecimalField(max_digits=15, blank=True, null=True,
		decimal_places=2, default=0.00, verbose_name="Valor distribuidor paquete")
	valorDC = models.DecimalField(max_digits=15, blank=True, null=True,
		decimal_places=2, default=0.00, verbose_name="Valor distribuidor caja")
	valorCC = models.DecimalField(max_digits=15, blank=True, null=True,
		decimal_places=2, default=0.00, verbose_name="Valor consumo caja")

	def __unicode__(self):
		return self.producto


	def save(self, *args, **kwargs):
		if self.valorVenta:
			self.valorIva = round(float(self.valorVenta) * IVA, 3)
			super(Producto, self).save(*args, **kwargs)
		else:
			self.valorIva=0
			super(Producto, self).save(*args, **kwargs)

producto/views.py
#-*- coding: utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Producto
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    UpdateView,
    CreateView,
    DeleteView
    )
from django.core.urlresolvers import reverse_lazy
#mixins
from django.contrib.auth.mixins import(
    LoginRequiredMixin, PermissionRequiredMixin)
from django.contrib.auth.decorators import (
    login_required, permission_required)


class ProductoInsert(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
	permission_required = ('producto.add_producto')
	model = Producto
	success_url = reverse_lazy('producto:producto_list')
	fields = ['codigo', 'producto', 'descripcion',
	 'valorDP','valorVenta','valorDC','valorCC' ]

class ProductoList(LoginRequiredMixin, ListView):
    # login
    model = Producto
    context_object_name = 'productos'
    # paginate_by = 5
    # def get_queryset(self, *args, **kwargs):
    #     qs = super(ProductoList, self).get_queryset(*args, **kwargs).order_by("producto")
    #     return qs
    #     #funcion para paginar una lista
    # def get_context_data(self, **kwargs):
    #     context = super(ProductoList, self). get_context_data(**kwargs)
    #     context['range'] = range(context["paginator"].num_pages)
    #     return context

class ProductoUpdate(LoginRequiredMixin,
                       PermissionRequiredMixin, UpdateView):
    permission_required = ('producto.change_producto')
    model = Producto
    success_url = reverse_lazy('producto:producto_list')
    fields = ['codigo', 'producto', 'descripcion',
              'valorDP','valorVenta','valorDC','valorCC']
#
# class InventarioDelete(LoginRequiredMixin,
#                        PermissionRequiredMixin, DeleteView):
# 	permission_required= ('inventario.delete_inventario')
# 	model = Inventario
# 	success_url = reverse_lazy('inventario:inventario_list')
#
@login_required()
def producto_detail(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    template = loader.get_template('producto/producto_detail.html')
    context = {
        'producto' : producto
    }
    return HttpResponse(template.render(context, request))
#
#

templates/producto/inventario_confirm_delete.html
{% extends "system_index.html" %}

{% block system_Contable %}
<a href="{%url 'inventario:inventario_list' %}"><span class="icon fa-arrow-left "></span></a>
<form method="post">
	{% csrf_token %}
    ¿Estás seguro que deseas borrar "{{ object }}"?
    <input type="submit" value="Borrar" />
</form>

{%endblock%}

templates/producto/producto_detail.html
{% extends "system_index.html" %}

{% block system_Contable %}

<div class="text-center">
  <h4 class="card-title">Codigo: {{producto.codigo}}</h4>
  <h4 class="card-title">Producto: {{producto.producto}}</h4>

</div>
<hr>

<div class="form-row">
        <div class="form-group col-md-3 ">
          Descripción: <br>{{producto.descripcion}}<hr>

        </div>
        <div class="form-group col-md-3 ">
          IVA Consumo Paquete:<br> ${{producto.valorIva}}<hr>

        </div>

</div>
<div class="form-row">
        <div class="form-group col-md-3 ">
          Valor Venta Consumo Paquete: <br>${{producto.valorVenta}}<hr>
        </div>
        <div class="form-group col-md-3 ">
          Valor Venta Distribuidor Paquete: <br>${{producto.valorDP}}<hr>
        </div>
        <div class="form-group col-md-3 ">
          Valor Venta Distribuidor Caja: <br>${{producto.valorDC}}<hr>
        </div>
        <div class="form-group col-md-3 ">
          Valor Venta Consumo caja: <br>${{producto.valorVenta}}<hr>
        </div>
</div>

{%endblock%}

templates/producto/producto_form.html
{% extends "system_index.html" %}

{% block system_Contable %}
<form method="post">
<a href=""><span class="icon fa-arrow-left "></span></a>
	<header>
        <center><h2>Elemento </h2></center><hr>
    </header>

		{% csrf_token %}
		<div class="form-row ">
			{%for field in form %}
				<div class="form-group col-md-4 ">
					{{ field.errors }}
					{{ field.label_tag }} <br> {{ field }}
				</div>
			{% endfor %}
		</div>

    <input type="submit" class="btn btn-success pull-right" value="Guardar" />
</form>
{%endblock%}

templates/producto/producto_list.html
{% extends "system_index.html" %}

{% block system_Contable %}


<table id="example1" class="table table-bordered table-striped">

    <thead>
        <tr>

            <th>Codigo</th>
            <th>Producto</th>
            <th>valor Iva</th>
            <th>valor Venta</th>

        </tr>
    </thead>
    <tbody>
    	{% for pr in productos %}
    		<tr>
    			<td>{{pr.codigo}}</td>
    			<td>{{pr.producto}}</td>
    			<td>{{pr.valorIva}}</td>
    			<td>{{pr.valorVenta}}</td>
          <td class="bg-info" >
            <a href="{%url 'producto:producto_detail' pr.id%}" class="fa fa-eye fa-2x"></a>
          </td>
          <td class="bg-warning" >
            <a href="{%url 'producto:producto_edit' pr.id%}"  class="fa fa-pencil-square-o fa-2x"></a>
          </td>
    		</tr>
    	{% endfor %}
    </tbody>
</table>

<!--
{% if is_paginated %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link bg-success text-white" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
    </li>
    {% endif %}

    {% for i in range %}
    <li class="page-item text-success"><a class="page-link text-success" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link bg-success text-white" href="?page={{ page_obj.next_page_number }}">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}-->

{%endblock%}