cliente/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
	url(r'^new', views.ClienteInsert.as_view(),
		name= "cliente_insert"),
	url(r'^list$', views.ClienteList.as_view(),
		name='cliente_list'),
    url(r'^cliente/update(?P<pk>[0-9]+)/$', views.ClienteUpdate.as_view(),
        name='cliente_update'),
    url(r'^cliente/detail(?P<pk>[0-9]+)/$', views.clienteDetail,
        name='cliente_detalle'),
	# url(r'^cliente/delete(?P<pk>[0-9]+)/$', views.ClienteDelete.as_view(),
	#  	name="cliente_delete"),
	# url(r'^(?P<pk>[0-9]+)/$', views.cliente_detail,
	# 	name="cliente_detail"),
]

factura/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^factura/venta$', views.facturaCrear, name="factura_venta"),
    url(r'^factura/search$', views.searchCliente, name='search_Cliente'),
    url(r'^factura/searchProducto$', views.searchProducto, name='search_Producto'),
    url(r'^factura/list$',views.FacturaList.as_view(),
        name='factura_list'),
    url(r'^factura/reporteAll', views.Generar_pdf, name='reporte_Facturas'),
    url(r'^factura/Pdf_Factura', views.PdfFactura.as_view(),
       name='reporte_Detalle_Factura'),
    url(r'^factura/facturas_rango_fecha', views.PdfFacturasRango.as_view(),
        name='factura_rango_fecha'),
    url(r'^factura/csv_facturas_rango_fecha', views.csv_facturas,
        name='csv_factura_rango_fecha'),

    # url(r'^factura$',
    # 	TemplateView.as_view(template_name="factura/factura_index.html"),
    # 	name="factura"),
    # url(r'^factura/new', views.FacturaInsert.as_view(),
    # 	name="factura_insert"),

    # url(r'^factura/edit(?P<pk>[0-9]+)/$',views.FacturaUpdate.as_view(),
    # 	name='factura_edit'),
    # url(r'^factura/(?P<pk>[0-9]+)/$', views.factura_detail,
	# 	name="factura_detail"),
    # url(r'^factura/detalle', views.DetalleFacturaInsert.as_view(),
    # 	name="detalle_factura_insert"),
    # #url(r'^factura/detalle(?P<pk>[0-9]+)/$', views.DetalleFacturaInsert.as_view(),
    # 	#name="detalle_factura_insert_esp"),


    #
    #
    # prueba de reporte estatico con reportLab
    # url(r'^factura/report/$', views.report),
]

plataforma/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import (
handler400, handler403, handler404, handler500
)
# from usuario import views as usuario_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('usuario.urls', namespace='usuario')),
    url(r'^producto/', include('producto.urls', namespace='producto')),
    #url(r'^', include('proveedor.urls', namespace='proveedor')),
    #url(r'^', include('inventario.urls', namespace='inventario')),
    url(r'^cliente/', include('cliente.urls', namespace = 'cliente')),
    url(r'^', include('factura.urls', namespace = 'factura')),
]+	static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

factura/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from cliente.models import Cliente
from producto.models import Producto
import decimal
from django.db.models import signals
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect
from django.db import IntegrityError
import usuario.urls

class Factura(models.Model):
	FORMA_PAGO= (
		('efectivo', 'Efectivo'), ('cheque', 'Cheque'),
		('tarjeta débito', 'Tarjeta débito'),
		('tarjeta crédito', 'Tarjeta crédito'),
		('venta a crédito','Venta a crédito'), ('bono','Bono'),
		('vale','Vale'), ('otros','Otros'),
		)
	serie = models.AutoField(primary_key=True, auto_created=True,
		serialize=False)#codigo de factura
	maquina = models.CharField(max_length=20, verbose_name="Máquina")#N Seriemaquina
	fecha = models.DateField(auto_now_add=True)#fecha de Venta
	vendedor = models.ForeignKey(User)
	cliente = models.ForeignKey(Cliente)
	formaPago = models.CharField(choices=FORMA_PAGO ,
		max_length=50, verbose_name='Forma de pago')
	iva = models.DecimalField(max_digits=15, decimal_places=2, default=0,
		null=True, blank=True)
	total = models.DecimalField(max_digits=15, default=0,
		decimal_places=2, null=True, blank=True)
	dineroRecibido = models.DecimalField(max_digits=15, default=0,
		decimal_places=2, null=True, blank=True)
	dineroDevuelto = models.DecimalField(max_digits=15, default=0,
		decimal_places=2, null=True, blank=True)
	def __str__(self):
		return str(self.serie)

	def subtotal(self):
		return self.total - self.iva


class DetalleFactura(models.Model):
	factura =models.ForeignKey(Factura, on_delete=models.CASCADE)
	producto = models.ForeignKey(Producto)
	descripcion = models.CharField(max_length=45, verbose_name="Descripción")
	precio = models.DecimalField(max_digits=15, decimal_places=2)
	cantidad = models.PositiveSmallIntegerField()
	valorIva = models.DecimalField(max_digits=15, decimal_places=2,
		verbose_name="Valor IVA")
	subtotal = models.DecimalField(max_digits=15, decimal_places=2)

	def __unicode__(self):
		return self.descripcion

	# def save(self, *args, **kwargs):
	# 	try:
	# 		consultaPrecio = Producto.objects.get(producto=self.producto)
	# 		self.precio = round(float(consultaPrecio.valorVenta))
	# 		self.valorIva = round(float(consultaPrecio.valorIva)*self.cantidad)
	# 		self.subtotal = round(float(self.precio)*self.cantidad)
	# 		#consultaPrecio.cantidad -= self.cantidad
	# 		consultaPrecio.save()
	# 		consultaFactura = Factura.objects.get(serie = str(self.factura))
	# 		consultaFactura.iva = round(float(consultaFactura.iva)) + round(float(self.valorIva))
	# 		consultaFactura.total = round(float(consultaFactura.total))+ round(float(self.subtotal))
	# 		consultaFactura.save()
	# 		super(DetalleFactura, self).save(*args, **kwargs)
	# 	except IntegrityError :
	# 		return redirect('factura:factura_insert')
	# 	else:
	# 		pass
	#
	# 	super(DetalleFactura, self).save(*args, **kwargs)
	#

# en ./manage.py shell
# from inventario.models import Inventario
# >>> producto = "cuchara soprera Tami"
# >>> precio = Inventario.objects.get(elemento=producto)
# >>> precio.cantidad
# 30

factura/forms.py
from .models import * # Change as necessary
from django.forms import ModelForm
from django import forms


class RangoForm (forms.Form):
    fecha_i = forms.DateField(widget = forms.TextInput(attrs={'class':'form-control', 'id':'Fecha_i', 'data-date-format':'dd/mm/yyyy'}))
    fecha_f = forms.DateField(widget = forms.TextInput(attrs={'class':'form-control', 'id':'Fecha_f', 'data-date-format':'dd/mm/yyyy'}))

factura/views.py
#-*- coding: utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
#importar http
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader, Context
#Vistas
from django.views.generic import ListView, TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    UpdateView,
    CreateView,
    DeleteView
    )
from django.contrib.auth.models import User
from .models import Factura, DetalleFactura
from django.core.urlresolvers import reverse_lazy
#mixins
from django.contrib.auth.mixins import(
    LoginRequiredMixin, PermissionRequiredMixin)
from django.contrib.auth.decorators import (
    login_required, permission_required)
#pdf Dionicio
import datetime
#por defecto se instala html5lib==0.999999999
#para que funciones pip install html5lib==1.0b8
import xhtml2pdf.pisa as pisa
import cStringIO as StringIO
from django import http
import cgi
import csv
#modelos
from cliente.models import Cliente
from producto.models import Producto
import json
import decimal
from django.core import serializers
#para facturaCrear
from django.template import RequestContext
from django.db import transaction
from django.contrib import messages
from django.template import RequestContext as ctx
from django.template import Context
from .forms import RangoForm
from django.utils import timezone

# Create your views here.
@login_required()
@permission_required('factura.add_factura')
def facturaCrear(request):
    IVA = 0.19
    form = None
    if request.method == 'POST':
        sid = transaction.savepoint()
        try:
            proceso = json.loads(request.POST.get('proceso'))
            print proceso
            print ("en try")
            if 'clienProv' not in proceso:
                msg = 'El cliente no ha sido seleccionado'
                raise Exception(msg)

            if len(proceso['producto']) <= 0:
                msg = 'No se ha seleccionado ningun producto'
                raise Exception(msg)

            total = 0#factura cuando se crea inicia en 0
            iva = 0

            for k in proceso['producto']:
                print (k['codigo'])
                producto = Producto.objects.get(codigo=k['codigo'])
                #subtotal = (producto.valorVenta) * int(k['cantidad'])
                valorIva = (float(k['valorVenta']) * IVA) * int(k['cantidad'])
                iva += valorIva

                subtotal = float(k['valorVenta']) * int(k['cantidad'])
                total +=subtotal
                #print ("en for")
                print(k['cantidad'])
                print producto
                #print subtotal
                #print total

            crearFactura = Factura(
                cliente = Cliente.objects.get(dni=proceso['clienProv']),
                fecha = timezone.now(),
                iva = iva,
                total = total,
                vendedor = request.user,
                formaPago = proceso['tipoPago'],
                maquina = proceso['idMaquina'],
                dineroRecibido = proceso['efectivo'],
                dineroDevuelto = proceso['devolver'],
            )
            crearFactura.save()
            print "Factura Guardada"
            print crearFactura
            for k in proceso['producto']:
                producto = Producto.objects.get(codigo=k['codigo'])
                print("en for detalle")
                print (producto)
                crearDetalle = DetalleFactura(
                    producto = producto,
                    descripcion = producto.descripcion,
                    cantidad = int(k['cantidad']),
                    valorIva = (float(k['valorVenta']) * IVA) * int(k['cantidad']),
                    precio = float(k['valorVenta']) - (float(k['valorVenta']) * IVA),
                    subtotal = float(k['valorVenta']) * int(k['cantidad']),
                    factura = crearFactura,
                )
                crearDetalle.save()
                print("despues de crearDetalle.save()\n\n" )
            messages.success(request, 'La venta se ha realizado')
        except Exception, e:
            try:
                transaction.savepoint_rollback(sid)
            except:
                pass
            messages.error(request, e)
    return render(request, 'factura/crear_factura.html', {} )
    #return render_to_response('factura/crear_factura.html', {'form': form}, context_instance=RequestContext(request))


#Busqueda ajax de usuarios
from django.db.models import Q

def searchCliente(request):
    dni = request.GET.get('dni')
    dnis= Cliente.objects.filter(Q(dni=dni)|Q(nombreEmpresa__icontains=dni)
        |Q(nombreRepresentante__icontains=dni)
        |Q(apellidoRepresentante__icontains=dni))#__startswith
    dnis = [cliente_serializer(cliente) for cliente in dnis]
    return HttpResponse(json.dumps(dnis), content_type='application/json')

def cliente_serializer(cliente):
    return{'dni':cliente.dni, 'nombreEmpresa':cliente.nombreEmpresa,
           'nombreRepresentante':cliente.nombreRepresentante,
           'apellidoRepresentante':cliente.apellidoRepresentante}

#productos
def searchProducto(request):
    codigo = request.GET.get('codigo')
    codigos = Producto.objects.filter(Q(codigo=codigo)
            |Q(producto__icontains=codigo))
    json = serializers.serialize('json', codigos,
                                 fields= ('codigo', 'producto',
                                 'valorIva', 'valorVenta','valorDP',
                                 'valorDC','valorCC'))
    return HttpResponse(json, content_type='application/json')

class FacturaList(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = ('factura.add_factura')
    model = Factura
    context_object_name = 'facturas'
    paginate_by = 5
    #ordenar de mayor a menor
    def get_queryset(self, *args, **kwargs):
        qs = super(FacturaList, self).get_queryset(*args, **kwargs).order_by("-serie")
        # print qs
        # print qs.first()
        return qs
        #funcion para paginar una lista
    def get_context_data(self, **kwargs):
        context = super(FacturaList, self). get_context_data(**kwargs)
        context['range'] = range(context["paginator"].num_pages)
        return context

#PDF's

#Funciones de Creacion de PDF
def write_pdf(template_src, context_dict):
    template = loader.get_template(template_src)
    context = Context(context_dict)
    html = template.render(context)
    result = StringIO.StringIO()
    pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("utf-8")), result)
    if not pdf.err:
        return http.HttpResponse(result.getvalue(),
                                 content_type = 'application/pdf')
    return http.HttpResponse('ocurrio un error al generar el reporte %s'% cgi.escape(html))

def Generar_pdf(request):
    ventas = Factura.objects.all()
    return write_pdf('factura/factura_all.html',
                     {'pagesize':'A6', 'ventas':ventas})
#Final de Funciones de Creacion de PDF legal

class PdfFactura(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    permission_required = ('factura.add_factura')
    def post(self, request, *args, **kwargs):
        buscar = request.POST['busqueda']
        print(buscar)
        ventas = DetalleFactura.objects.filter(factura=buscar).order_by("-producto")
        datoFactura = Factura.objects.filter(serie=buscar)
        return write_pdf('factura/factura_Detalle.html',
                         { 'ventas':ventas, 'pagesize':'A6', 'datoFactura':datoFactura})


#en pdf
class PdfFacturasRango(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    permission_required = ('factura.add_factura')
    def post(self, request, *args, **kwargs):
        buscarFechaInicio = request.POST['busqueda-fechaInicio']
        buscarFechaFinal = request.POST['busqueda-fechaFinal']
        print(buscarFechaInicio)
        print(buscarFechaFinal)
        ventasRangoFechas = Factura.objects.filter(fecha__range=(buscarFechaInicio, buscarFechaFinal))
        return write_pdf('factura/reporte_facturas_fecha.html',
                         { 'ventasRangoFechas':ventasRangoFechas,
                          'pagesize':'A6'})

def csv_facturas(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Desposition']='attachment; filename=factura.csv'
    writer = csv.writer(response)
    writer.writerow(['SERIE', 'FECHA', 'IVA', 'TOTAL', 'VENDEDOR'])
    buscarFechaInicio = request.POST['busqueda-fechaInicio']
    buscarFechaFinal = request.POST['busqueda-fechaFinal']
    ventasRangoFechas = Factura.objects.filter(fecha__range=(buscarFechaInicio, buscarFechaFinal))
    for datos in ventasRangoFechas:
        writer.writerow([datos.serie, datos.fecha, datos.iva, datos.total, datos.vendedor])
    return response

templates/factura/detallefactura_form.html
{%extends "system_index.html"%}

{% block system_Contable %}

<ul>
<form method="post">
<a href="{%url 'factura:factura_detail' 11%}"><span class="icon fa-arrow-left "></span></a>

	<header>
				<h2>Detalles</h2>
	</header>



		{% csrf_token %}
		{{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

templates/factura/factura_Detalle.html
<\<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Reporte de facturas</title>
		<!--se llama el tamaño que se mensiono en la vista margin: 1cm;-->
		<style type="text/css">
			@page {
					size: 8.0cm 30cm;

					margin-left: 0.5cm;
					margin-right: 0.5cm;
					@frame footer {
							-pdf-frame-content: footerContent;
							bottom: 0cm;
							margin-left: 9cm;
							margin-right: 9cm;
							height: 1cm;
						}
					}
		</style>
	</head>
	<body>

				<center><p>DISTRIBUIDORA DESECHABLES EL MAYORISTA <br>
						Calle 11 No.9-86, Chiquinquirá (Boyacá)<br>
						Tel: 310 569 6085  -  321 921 2008 <br>
			    	JAIME H. QUINTERO RODRÍGUEZ
		        NIT. 5657839-0</br>
		        Regimen común
				</p><center>

    {% for algo in datoFactura %}
			<p align="left">
				FACTURA DE VENTA: {{algo.serie}} </br>
				Fecha: {{algo.fecha}} <br>
				Vendedor: {{algo.vendedor.id}} - {{algo.vendedor}}
				Máquina: {{algo.maquina}}<br>
				Cliente:{{algo.cliente.apellidoRepresentante}}   
				Nit: {{algo.cliente}}<br>
				Ciudad: {{algo.cliente.ciudad}}
				Dirección: {{algo.cliente.direccion}} <br>
				Teléfono: {{algo.cliente.telefono}} <br>
			</p>
			<hr>
		{% endfor %}

		<p align="left">
			PROD -- CANT -- VAL/UD -- IVA -- VAL/TOT<br>
			{% for factura in ventas %}
				{{factura.producto}} -- {{factura.cantidad}} --
				{{factura.precio}} -- {{factura.valorIva}} -- {{factura.subtotal}}<br>
			{% endfor %}</p>
		<hr>

		<p align="left">
      {% for algo in datoFactura %}
				FORMA DE PAGO: {{algo.formaPago}}
				SUBTOTAL: ${{algo.subtotal}} <br>
				IVA: ${{algo.iva}}
				TOTAL: ${{algo.total}} <br>
				EFECTIVO: $ {{algo.dineroRecibido}}
				CAMBIO: $ {{algo.dineroDevuelto}}
			{% endfor %}</p>

	</body>
</html>

templates/factura/factura_all.html
<\<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Reporte de facturas</title>
		<!--se llama el tamaño que se mensiono en la vista-->
		<style type="text/css">
			@page {
					size: {{ pagesize }};
					margin: 1cm;
					@frame footer {
							-pdf-frame-content: footerContent;
							bottom: 0cm;
							margin-left: 9cm;
							margin-right: 9cm;
							height: 1cm;
						}
					}
		</style>
	</head>
	<body>

		<div id="headerContent">
		    <center> <h1>EL MAYORISTA</h1>
		    <h3>Direccion: Cra 10 # , Chiquinquirá, Boyacá</h3>
		    <h3>Télefono: </h3>
		   <h3>NIT: </h3>
		   </div>
		 </br><center> <h2> REPORTE DE FACTURAS </h2>



		<table id="example1" class="table table-bordered table-striped">
	    <thead>
	        <tr>
	            <th style="border:1px solid black; padding: 2px;">Serie</th>
	            <th style="border:1px solid black; padding: 2px;">Maquina</th>
	            <th style="border:1px solid black; padding: 2px;">Vendedor</th>
	            <th style="border:1px solid black; padding: 2px;">Cliente</th>
	        </tr>
	    </thead>
	    <tbody>

		    	{% for factura in ventas %}
		    		<tr>
		    			<td style="border:1px solid black; padding: 2px;">{{factura.serie}}</td>
		    			<td style="border:1px solid black; padding: 2px;">{{factura.maquina}}</td>
		    			<td style="border:1px solid black; padding: 2px;">{{factura.vendedor}}</td>
		    			<td style="border:1px solid black; padding: 2px;">{{factura.cliente}}</td>

		    		</tr>
		    	{% endfor %}
		    {# {% endif %}#}
	    </tbody>
	</table>


	</body>
</html>

templates/factura/factura_detail.html
{% extends "system_index.html" %}

{% block system_Contable %}
<a href="{%url 'factura:factura_list' %}"><span class="icon fa-arrow-left "></span></a>
<h2>Factura : {{factura.serie}}</h2>
<ul>

	<li><b>Maquina: </b>{{factura.maquina}}</li>
	<li><b>Fecha: </b>{{factura.fecha}}</li>
	<li><b>Vendedor: </b>{{factura.vendedor}}</li>
	<li><b>Cliente: </b>{{factura.cliente}}</li>
	<li><b>Forma de pago: </b>{{factura.formaPago}}</li>
	<li><b>iva: </b>{{factura.iva}}</li>
	<li><b>Total: </b>{{factura.total}}</li>
</ul>

{%endblock%}

templates/factura/factura_form.html
{% extends "system_index.html" %}

{% block system_Contable %}
<form method="post">
<a href="{%url 'factura:factura_list' %}"><span class="icon fa-arrow-left "></span></a>
	<header>
        <h2>Factura </h2>
    </header>

    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" />
</form>
{%endblock%}

templates/factura/factura_index.html
{% extends "system_index.html" %}


{% block system_Contable %}

<h2>Factura</h2>

<form>
	<input type="text" name="" placeholder="">
</form>




{%endblock %}

templates/factura/factura_list.html
{% extends "system_index.html" %}

{% block system_Contable %}



<div class="form-row">
      <div class="form-group col-md-4 ">
            <div class="busqueda">
                  <form class="navbar-search pull-left" method="POST" name="detalle_factura" action="{%url 'factura:reporte_Detalle_Factura'%}">{% csrf_token%}
                      <input title="se requiere numero" type="number" name="busqueda" class="search-query" placeholder="Buscar factura"  required>
                      <div class="btn-group">
                          <button class="btn btn-success" type="submit"><i class="icon fa fa-file-pdf-o"></i></button>
                      </div>
                  </form>
            </div>
      </div>
      <div class="form-group col-md-4 ">
              <div class="busqueda-fecha-rango">
                <label for="">facturas por fecha</label>
                <button type="button" class="btn btn-success fa fa-search" data-toggle="modal" data-target="#FacturasRangoFechaModal"></button>
              </div>
      </div>
      <div class="form-group col-md-4 ">
        <div class="pdf">
            <form class="navbar-search pull-left" method="POST" action="{%url 'factura:reporte_Facturas'%}">{% csrf_token%}
              <label >Reporte ventas totales</label>
              <button class="btn btn-success" type="submit"><i class="icon fa fa-file-pdf-o"></i></button>
            </form>
        </div>
      </div>
</div>

<!--modal-->
<!-- producto modal-->
<div class="modal fade" id="FacturasRangoFechaModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Reporte de facturas por fecha</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="{%url 'factura:csv_factura_rango_fecha'%}"  id="f-rango-fecha">
          {% csrf_token%}
          <div class="form-row">
            <div class="form-group col-md-5 ">
              <label for="inputEmail4">Fecha Inicio</label>
              <input name="busqueda-fechaInicio" id="b-f-fechaInicio" type="date" class="form-control fa fa-calendar" placeholder="30-12-2017"  min="2017-04-01" max="2050-12-20" required>
            </div>
            <div class="form-group col-md-5">
              <label for="inputPassword5">fecha Final</label>
              <input name="busqueda-fechaFinal" id="b-f-fechaFinal" type="date" class="form-control fa fa-calendar" placeholder="30-12-2017" min="2017-04-01" max="2050-12-20" required>
            </div>
            <div class="form-group col-md-2 ">
              <label for="inputAddress"></label>
              <button type="submit"  class="btn btn-success fa fa-file-excel-o"></button>
            </div>
            </div>
          </form>
<!--pdf -->
    <form method="POST" action="{%url 'factura:factura_rango_fecha'%}"  id="f-rango-fecha">
        {% csrf_token%}
        <div class="form-row">
          <div class="form-group col-md-5 ">
            <label for="inputEmail4">Fecha Inicio</label>
            <input name="busqueda-fechaInicio" id="b-f-fechaInicio" type="date" class="form-control fa fa-calendar" placeholder="30-12-2017"  min="2017-04-01" max="2050-12-20" required>
          </div>
          <div class="form-group col-md-5">
            <label for="inputPassword5">fecha Final</label>
            <input name="busqueda-fechaFinal" id="b-f-fechaFinal" type="date" class="form-control fa fa-calendar" placeholder="30-12-2017" min="2017-04-01" max="2050-12-20" required>
          </div>
          <div class="form-group col-md-2 ">
            <label for="inputAddress"></label>
            <button type="submit"  class="btn btn-success fa fa-file-pdf-o"></button>
          </div>

          </div>
        </form>
<!--pdf -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
      <p class="text-justify">
      Para abrir con excel solo da click derecho sobre el archivo y abrir con Excel o
      arrastra el archivo a Excel.</br> </br>
      Las operaciones matematicas cuando lo abras con Excel. </br>
      inicialmente abre con bloc de notas y con control+f o control+b busca los puntos(.)
      de valores numericos y cambialos por comas(;) esto te permitira hacer
      operaciones matematicas cuando lo abras con excel.
      </p>


    </div>
  </div>
</div>
</div>
<!--producto fin modal-->

<table class= "table table-striped table-responsive">
  <thead class="">
    <tr class="">
      <th scope="col">Factura</th>
      <th scope="col">Fecha</th>
      <th scope="col">Vendedor</th>
      <th scope="col">Cliente</th>
      <th scope="col">Iva</th>
      <th scope="col">Total</th>
    </tr>
  </thead>
  <tbody>
    {% for pr in facturas %}
    <tr>
      <td>{{pr.serie}}</td>
      <td>{{pr.fecha}}</td>
      <td>{{pr.vendedor}}</td>
      <td>{{pr.cliente}}</td>
      <td>{{pr.iva}}</td>
      <td>{{pr.total}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% if is_paginated %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link bg-success text-white" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
    </li>
    {% endif %}

    {% for i in range %}
    <li class="page-item text-success"><a class="page-link text-success" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link bg-success text-white" href="?page={{ page_obj.next_page_number }}">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}



{%endblock%}