cliente/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
	url(r'^new', views.ClienteInsert.as_view(),
		name= "cliente_insert"),
	url(r'^list$', views.ClienteList.as_view(),
		name='cliente_list'),
    url(r'^cliente/update(?P<pk>[0-9]+)/$', views.ClienteUpdate.as_view(),
        name='cliente_update'),
    url(r'^cliente/detail(?P<pk>[0-9]+)/$', views.clienteDetail,
        name='cliente_detalle'),
	# url(r'^cliente/delete(?P<pk>[0-9]+)/$', views.ClienteDelete.as_view(),
	#  	name="cliente_delete"),
	# url(r'^(?P<pk>[0-9]+)/$', views.cliente_detail,
	# 	name="cliente_detail"),
]

factura/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
#from recursos import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^factura/venta$', views.facturaCrear, name="factura_venta"),
    url(r'^factura/search$', views.searchCliente, name='search_Cliente'),
    url(r'^factura/searchProducto$', views.searchProducto, name='search_Producto'),
    url(r'^factura/list$',views.FacturaList.as_view(),
        name='factura_list'),
    url(r'^factura/reporteAll', views.Generar_pdf, name='reporte_Facturas'),
    url(r'^factura/Pdf_Factura', views.PdfFactura.as_view(),
       name='reporte_Detalle_Factura'),
    url(r'^factura/facturas_rango_fecha', views.PdfFacturasRango.as_view(),
        name='factura_rango_fecha'),
    url(r'^factura/csv_facturas_rango_fecha', views.csv_facturas,
        name='csv_factura_rango_fecha'),

    # url(r'^factura$',
    # 	TemplateView.as_view(template_name="factura/factura_index.html"),
    # 	name="factura"),
    # url(r'^factura/new', views.FacturaInsert.as_view(),
    # 	name="factura_insert"),

    # url(r'^factura/edit(?P<pk>[0-9]+)/$',views.FacturaUpdate.as_view(),
    # 	name='factura_edit'),
    # url(r'^factura/(?P<pk>[0-9]+)/$', views.factura_detail,
	# 	name="factura_detail"),
    # url(r'^factura/detalle', views.DetalleFacturaInsert.as_view(),
    # 	name="detalle_factura_insert"),
    # #url(r'^factura/detalle(?P<pk>[0-9]+)/$', views.DetalleFacturaInsert.as_view(),
    # 	#name="detalle_factura_insert_esp"),


    #
    #
    # prueba de reporte estatico con reportLab
    # url(r'^factura/report/$', views.report),
]

plataforma/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import (
handler400, handler403, handler404, handler500
)
# from usuario import views as usuario_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('usuario.urls', namespace='usuario')),
    url(r'^producto/', include('producto.urls', namespace='producto')),
    #url(r'^', include('proveedor.urls', namespace='proveedor')),
    #url(r'^', include('inventario.urls', namespace='inventario')),
    url(r'^cliente/', include('cliente.urls', namespace = 'cliente')),
    url(r'^', include('factura.urls', namespace = 'factura')),
]+	static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

producto/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
	url(r'^new', views.ProductoInsert.as_view(),
		name="producto_insert"),
	url(r'^list$', views.ProductoList.as_view(),
		name='producto_list'),
	url(r'^edit(?P<pk>[0-9]+)/$', views.ProductoUpdate.as_view(),
    	name='producto_edit'),
	#  url(r'^inventario/delete(?P<pk>[0-9]+)/$', views.InventarioDelete.as_view(),
	#  	name="inventario_delete"),
	url(r'^(?P<pk>[0-9]+)/$', views.producto_detail,
		name="producto_detail"),
]

usuario/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
    #url(r'^$', TemplateView.as_view(template_name="index.html"), name="index"),
    #url(r'^login/$', views.authentication, name="authentication"),
    url(r'^$', views.authentication, name="authentication"),
    url(r'^plataforma', views.systemIndex, name="system_index"),
    url(r'^perfil/new', views.PerfilInsert.as_view(), name="perfil_insert"),
    url(r'^perfil/list$',views.PerfilList.as_view(), name='perfil_list'),
    url(r'^perfil/edit(?P<pk>[0-9]+)/$',views.PerfilUpdate.as_view(),
    	name='perfil_edit'),
	url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name="logout"),

    url(r'^pagina_quienesSomos', views.paginaquienesSomos, name='pagina_quienesSomos'),
    url(r'^pagina_Cubiertos', views.paginaCubiertos, name='pagina_Cubiertos'),
    url(r'^pagina_Bolsas', views.paginaBolsas, name='pagina_Bolsas'),
    url(r'^pagina_ProInstitucional', views.paginaProInstitucional,
        name='pagina_ProInstitucional'),
    url(r'^pagina_Pinateria', views.paginaPinateria, name='pagina_Pinateria'),
    url(r'^pagina_LagunaFuquene', views.paginaLagunaFuquene,
        name='pagina_LagunaFuquene'),
    url(r'^pagina_FloresGuavata', views.paginaFloresGuavata,
        name='pagina_FloresGuavata'),
    url(r'^pagina_Cooperativismo', views.paginaCooperativismo,
        name='pagina_Cooperativismo'),

]

templates/base_factura.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {%load staticfiles%}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <!-- Compatible con monbiles -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static "css/bootstrap.css"%}">
    <link rel="stylesheet" href="{% static "css/font-awesome.css"%}">
    <link rel="icon" href="{% static "images/icono.ico" %}" >
  </head>
  <body>

    <h2> DISTRIBUIDORA DESECHABLES </br> EL MAYORISTA </h2>
    <h6><p> "La variedad y la atención </br> marcan la diferencia"</br>
          Calle 11 No.9-86, Chiquinquirá (Boyacá)</br>
            Tel: 310 569 6085  -  321 921 2008</br>
            JAIME HELI QUINTERO RODRÍGUEZ</br>
            NIT. 5657839-0 Regimen común
          </p></h6>
    <section class="container mt-5 pt-2">
      {% block factura %}
      {% endblock %}
    </section>






    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS  la que sigue es de otro proyect-->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="{%static "js/bootstrap.min.js"%}" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" ></script>
    <script type="text/javascript" src="{% static "js/ajax.js" %}"></script>

    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>-->
  </body>
</html>

templates/base_paginas.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {%load staticfiles%}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <!-- Compatible con monbiles -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    -->
    <link rel="stylesheet" href="{% static "css/bootstrap.css"%}">
    <link rel="stylesheet" href="{% static "css/font-awesome.css"%}">
    <link rel="icon" href="{% static "images/icono.ico" %}" >
    <title>El Mayorista</title>

  </head>
  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-success">
      <a class="navbar-brand" href="{% url 'usuario:index' %}">
        <img src= {% static "images/logo.png" %} width="30" height="30" class="d-line-block aling-top" alt="logo">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <div class="navbar-nav mr-auto text-center">


          <a class="nav-item- nav-link active active" href="{% url 'usuario:pagina_quienesSomos' %}">¿Quienes somos?</a>


          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" data-toggle="dropdown">Productos</a>
            <div class="dropdown-menu">
              <a class="dropdown-item"  href="{% url 'usuario:pagina_Bolsas' %}">Bolsas</a>
              <a class="dropdown-item"  href="{% url 'usuario:pagina_Cubiertos' %}">Cubiertos</a>
              <a class="dropdown-item"  href="{% url 'usuario:pagina_ProInstitucional' %}">Productos institucionales</a>
              <a class="dropdown-item"  href="{% url 'usuario:pagina_Pinateria' %}">Piñateria</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" data-toggle="dropdown">Noticias</a>
            <div class="dropdown-menu">
              <a class="dropdown-item"  href="">Laguna de Fúquene</a>
              <a class="dropdown-item"  href="">Guavata: Ruta De Las Flores</a>
              <a class="dropdown-item"  href="">Cooperativismo</a>
            </div>
          </li>

          <a class="nav-item- nav-link active" href="#contacto">Contactanos</a>
          <a class="nav-item- nav-link active fa fa-envelope fa-2x" href="https://corporativo.mi.com.co/" target="_blank"></a>


          {% if user.is_authenticated %}

            <a class="nav-item- nav-link fa fa-user-circle fa-2x p-3 mb-2 bg-light text-dark mr-5 ml-5" href="{% url 'usuario:system_index' %}"></a>

            <button type="button" onclick="window.location.href={%url 'usuario:logout'%}" class="btn btn-outline-danger mr-5 ml-5">Cerrar Sesión</button>

          {% else %}
            <button type="button" onclick="window.location.href={% url 'usuario:authentication' %}" class="btn btn-outline-dark mr-5 ml-5">Iniciar sesión</button>
          {%endif%}


            </div>
        </div>
      </div>
    </nav>



    {% block paginas %}
    {% endblock %}



    <footer class="container-fluid bg-success mt-5 pt-2" id="contacto">
      <div class="row text-white py-4 text-white  text-center justify-content-center ">

                <div class="col-md-4">
                  <h6 class="lead"> Contactanos</h6>
                  <a href="mailto:almacen@desechableselmayorista.com.co" class="lead"><span class="label">almacen@desechableselmayorista.com.co</span></a></br>
                  <a href="https://www.facebook.com/Desechables-El-Mayorista-968627966610048/" target="_blank"> <span class="fa fa-facebook fa-2x" ></span></a>
                </div><br><br>
                <div class="col-md-4 " >
                    <h6 class="lead"> Chiquinquirá - Boyacá <br>
                    Carrera 10 # 11-18<br>
                    Telefonos: 310 569 6085 - 313 207 1454
                    </h6>
                </div>
                <div class="col-md-4 " >
                      <h6 class="lead"> Desarrollado por: <br><br>
                      <a href="http://www.hoodeddeveloper.com/"  target="_blank">  <img src= {% static "images/Logo-Hooded-Developer.png" %}  alt="logo hooded developer" width="auto" height="60px" class="rounded mx-auto d-block"></a>
                    </h6>
                </div>
        </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS  -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="{%static "js/bootstrap.min.js"%}" crossorigin="anonymous"></script>
    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>-->
  </body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    {%load staticfiles%}
    <meta charset="utf-8">
    <!-- Compatible con monbiles -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    -->
    <link rel="stylesheet" href="{% static "css/bootstrap.css"%}">
    <link rel="stylesheet" href="{% static "css/font-awesome.css"%}">
    <link rel="icon" href="{% static "images/icono.ico" %}" >
    <style>
      .slider{
        background: url({%static "images/fachada.jpg"%});
        height: 75vh;/*abarque el 100% dispositivo*/
        background-size: cover;
        background-position: center;
        background-color:gray; opacity:1;
      }
    </style>
  </head>
  <body>
    <section class="container-fluid slider d-flex justify-content-center align-items-center" id="inicio">
      <form action="" method="post" class= "text-light">
          {% csrf_token %}
        <div class="form-group">
          <label for="exampleInputEmail1">Usuario</label>
          <input type="text" name="username" class="form-control" id="" aria-describedby="emailHelp" placeholder="Usuario">
          <small id="emailHelp" class="form-text ">Nunca comparta su usuario y contraseña</small>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Contraseña</label>
          <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Contraseña">
        </div>
        <button type="submit" name="action" value="login" class="btn btn-success" >Ingresar</button>
        <hr>

      </form>
    </section>

    <footer class="container-fluid bg-success" id="contacto">
      <div class="row text-white py-4 text-white  text-center justify-content-center ">
                <div class="col-md-4 " >
                      <h6 class="lead"> Desarrollado <br><br>
                      <a href="http://www.hoodeddeveloper.com/"  target="_blank">  <img src= {% static "images/Logo-Hooded-Developer.png" %}  alt="logo hooded developer" width="auto" height="60px" class="rounded mx-auto d-block"></a>
                    </h6>
                </div>

                <div class="col-md-4 " >
                    <h6 class="lead"> Chiquinquirá - Boyacá <br>
                    Carrera 10 # 11-18<br>
                    Telefonos: 310 569 6085 - 313 207 1454
                    </h6>
                </div>

                <div class="col-md-4">
                  <h6 class="lead"> Contactanos</h6>
                  <a href="mailto:almacen@desechableselmayorista.com.co" class="lead"><span class="label">almacen@desechableselmayorista.com.co</span></a></br>
                  <a href="https://www.facebook.com/Desechables-El-Mayorista-968627966610048/" target="_blank"> <span class="fa fa-facebook fa-2x" ></span></a>
                </div>
        </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS  -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="{%static "js/bootstrap.min.js"%}" crossorigin="anonymous"></script>
    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>-->
</body>
</html>

templates/system_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {%load staticfiles%}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <!-- Compatible con monbiles -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    pruba de calendario
    <script src="{% static "libs/jquery.js"%}" charset="utf-8"></script>
    <script src="{% static "libs/bootstrap-datepicker/js/bootstrap-datepicker.min"%}" charset="utf-8"></script>
    <link rel="stylesheet" href="{% static "libs/bootstrap-datepicker/css/bootstrap-datepicker.css"%}">
    -->

    <link rel="stylesheet" href="{% static "css/bootstrap.css"%}">
    <link rel="stylesheet" href="{% static "css/font-awesome.css"%}">
    <link rel="icon" href="{% static "images/icono.ico" %}" >
    <style>
      .slider{
        background: url({%static "images/Platzi-Stiker.jpeg"%});
        height: 100vh;/*abarque el 100% dispositivo*/
        background-size: cover;
        background-position: center;
        background-color:gray; opacity:1;
      }

    </style>
  </head>
  <body>



    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-success">
      <a class="navbar-brand" href="{% url 'usuario:system_index' %}">
        <img src="{% static "images/logo.png" %}" width="30" height="30" class="d-line-block aling-top" alt="logo">
        {{user.username}}
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <div class="navbar-nav mr-auto text-center">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Perfil</a>
            <div class="dropdown-menu">
              {% if not user.perfil%}
              <a class="dropdown-item" href="{% url 'usuario:perfil_insert' %}">Crear</a>
              {% endif %}
              <a class="dropdown-item" href="{% url 'usuario:perfil_list' %}">Visualizar</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="">Factura</a>
            <div class="dropdown-menu">
              <a class="dropdown-item"  href="{% url 'factura:factura_venta'%}">Crear</a>
              <a class="dropdown-item"  href="{% url 'factura:factura_list'%}">visualizar</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="" >Cliente</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'cliente:cliente_insert' %}">Crear</a>
              <a class="dropdown-item" href="{%url 'cliente:cliente_list'%}">Visualizar</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="">Productos</a>
            <div class="dropdown-menu">
              <a class="dropdown-item"  href="{% url 'producto:producto_insert' %}">Crear</a>
              <a class="dropdown-item"  href="{%url 'producto:producto_list' %}">visualizar</a>
            </div>
          </li>
          <a class="nav-item- nav-link active fa fa-envelope fa-2x" href="https://corporativo.mi.com.co/" target="_blank"></a>
          <button type="button" onclick="window.location.href={%url 'usuario:logout'%}" class="btn btn-outline-danger">Cerrar Sesión</button>
        </div>
      </div>
    </nav>

    <section class="container mt-5 pt-2">
      {% block system_Contable %}
      {% endblock %}
    </section>


    <footer class="container-fluid bg-success mt-5 pt-2" id="contacto">
      <div class="row text-white py-4 text-white  text-center justify-content-center ">

                <div class="col-md-4">
                  <h6 class="lead"> Contactanos</h6>
                  <a href="mailto:almacen@desechableselmayorista.com.co" class="lead"><span class="label">almacen@desechableselmayorista.com.co</span></a></br>
                  <a href="https://www.facebook.com/Desechables-El-Mayorista-968627966610048/" target="_blank"> <span class="fa fa-facebook fa-2x" ></span></a>
                </div><br><br>
                <div class="col-md-4 " >
                    <h6 class="lead"> Chiquinquirá - Boyacá <br>
                    Carrera 10 # 11-18<br>
                    Telefonos: 310 569 6085 - 313 207 1454
                    </h6>
                </div>
                <div class="col-md-4 " >
                      <h6 class="lead"> Desarrollado por: <br><br>
                      <a href="http://www.hoodeddeveloper.com/"  target="_blank">  <img src= {% static "images/Logo-Hooded-Developer.png" %}  alt="logo hooded developer" width="auto" height="60px" class="rounded mx-auto d-block"></a>
                    </h6>
                </div>
        </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS  la que sigue es de otro proyect-->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="{%static "js/bootstrap.min.js"%}" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" ></script>
    <script type="text/javascript" src="{% static "js/ajax.js" %}"></script>

    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>-->
  </body>
</html>